apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-29T02:45:23Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1798"
  uid: bb7686ef-b67a-461b-83d2-a047c81e28be
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.97.255.230
  clusterIPs:
  - 10.97.255.230
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32161
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
