apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-recreate-service
  labels:
    app: spring-petclinic-recreate
spec:
  type: LoadBalancer
  ports:
  - port: 9966
    targetPort: 9966
    protocol: TCP
  selector:
    app: spring-petclinic-recreate